### ISSUE TITLE
vim keymapping?

### ISSUE THREAD

**Issue by KyleAMathews** [ForbesLindesay/react-code-mirror#7]
How would I go about adding Vim (or other) keymapping? Right now it just throws an error.

**Comment by ForbesLindesay** [comment]
What have you tried?  We pass all of `this.props` to code-miror as options.  Anything else could be added by us adding additional properties, or by code-mirror accepting additional configuration via options.

**Comment by gynet** [comment]
Any way to enable it easily? Currently, the keymap/vim.js will throw exceptions

**Comment by gynet** [comment]
Tried:


(function () {
  var makeCursorFat = function() {
    var style = document.createElement('style');
    style.textContent =
    'div.CodeMirror div.CodeMirror-cursor { ' +
      'width: auto; ' +
      'border: 0; ' +
      'background: transparent; ' +
      'background: rgba(0, 200, 0, .4); ' +
    '} ';
    document.head.appendChild(style);
  }

  var addScript = function(callback) {
    var scr = document.createElement('script');
    scr.src = 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.22.0/keymap/vim.js';
    scr.onload = callback;
    document.head.appendChild(scr);
  }

  var retryInterval = 1000;

  var vimify = function () {
    var editorElement = document.querySelector('#text-editor > div.CodeMirror');

    if (editorElement) {
      editorElement.CodeMirror.options.keyMap = 'vim';
      editorElement.CodeMirror.options.showCursorWhenSelecting = 'vim';
      makeCursorFat();
      console.log('VIMification complete!');
    } else{
      retryInterval = retryInterval * 2;
      if (retryInterval < 20000) {
        console.log('Retrying to VIMify... ' + retriesLeft);
        window.setTimeout(vimify, retryInterval);
      }
      return;
    }
  };

  addScript(vimify);
}());

**Comment by ForbesLindesay** [comment]
@gynet this is for the react implementation of codemirror.  It does not look like you are using the react implementation.

**Comment by gynet** [comment]
@ForbesLindesay  I am using the "leetcode.com". It looks like using the react implementation of codemirror.  Could you help to provide any way to enable the vim mode on the client side?
